### ISSUE TITLE
Not working. Syntax Error

### ISSUE THREAD

**Issue by akrigline** [Ethck/module-collapse#1]
Core 0.8.9 - 5e 1.5.2 - Electron

Loading up my module management window I get this in console:
```
Uncaught (in promise) Error: Syntax error, unrecognized expression: #module-list #DatDamnZotz-[DatDamnZotz#7962] ul
    at Function.se.error (jquery.min.js:2)
    at se.tokenize (jquery.min.js:2)
    at Function.se [as find] (jquery.min.js:2)
    at S.fn.init.find (jquery.min.js:2)
    at module.js:98
    at Array.forEach (<anonymous>)
    at module.js:80
    at Function._call (foundry.js:194)
    at Function.call (foundry.js:179)
    at ModuleManagement._render (foundry.js:2097)
```

Happens in a world with only map packs plus:
- Moulinette (and its 5 submodules)
- Compendium Scene Viewer
- Token Attacher (because of Bailywiki)
- Animation Preview

**Comment by akrigline** [comment]
Also there's a lot of console logs. May I recommend a devmode debug flag?

**Comment by Ethck** [comment]
Did I not push a version or something? I'm not seeing a single console.log in the codebase locally... Time to investigate I guess.

**Comment by Ethck** [comment]
Weird, no log statements in the code in remote either (at least in default branch)

**Comment by Ethck** [comment]
Based on the error this is because DatDamnZodtz's username also includes brackets... I guess I need to filter those out as well.
